### ISSUE TITLE
how to resize

### ISSUE THREAD

**Issue by ctuser** [BigBadaboom/androidsvg#102]
How can I render to a specific size?
Tried a few of the render functions, tried around with get/setRenderDPI... but it always renders at the same pixel size (here: 192x192 which is correct original svg px size). how can i get it to render at higher sizes, e.g. 1024x1024?

**Comment by BigBadaboom** [comment]
To get an SVG to scale, it needs to have a `viewBox` attribute. You can read about how that works in the SVG spec. There are also many tutorials on the web.  For example:

https://sarasoueidan.com/blog/svg-coordinate-systems/

Good luck

**Comment by sonyagutierrez12** [comment]
#100

**Comment by ShkurtiA** [comment]
In case it helps someone, I needed to resize it x10 and this is my result:

```
final SVG svg = SVG.getFromInputStream(inputStream);
svg.setDocumentViewBox(0, 0, 10* (int)svg.getDocumentViewBox().width(), 10* (int)svg.getDocumentViewBox().height());
svg.setDocumentWidth(10 * 100 + "%");
svg.setDocumentHeight(10 * 100 +"%");
final Picture picture = svg.renderToPicture((int)svg.getDocumentViewBox().width(),
                 (int)svg.getDocumentViewBox().height());
```

**Comment by BigBadaboom** [comment]
@ShkurtiA Your code looks a bit odd. What were you trying to do exactly?

- Scaling the viewBox width and height components by 10x will have the effect of reducing the scale by 10x.
- Setting the document width and height to 1000% should cancel that out
- Finally setting the viewport width and height in `renderToPicture()` only sets the size of the `Picture`. Which only affects the Picture coordinate scale, and does not really affect the final rendering.

So, as far as I can see, the following code should be equivalent to yours.

```
final SVG svg = SVG.getFromInputStream(inputStream);
svg.setDocumentViewBox(0, 0, (int)svg.getDocumentViewBox().width(), (int)svg.getDocumentViewBox().height());
svg.setDocumentWidth("100%");
svg.setDocumentHeight("100%");
final Picture picture = svg.renderToPicture();
```

And, in fact, most SVGs the `setDocumentViewBox()` will do nothing.  So that line will have no real effect either.

**Comment by ShkurtiA** [comment]
@BigBadaboom
Sorry for the late reply. The idea is that I was trying to find a way to generate icons for different screen resolution from the svg file. The designers deliver the svg for mdpi and based on device that I run the code, I generate an icon on that dpi, which means if its xhdpi, I need to multiply it with 2. Multiplying with 10 was just an example and currently that code is working for me.
Thanks for your reply and work.
