### ISSUE TITLE
Feature Request: Set manual stroke width used by SVGAndroidRenderer

### ISSUE THREAD

**Issue by AlecStrong** [BigBadaboom/androidsvg#107]
I'd like to be able to specify the stroke width for an entire SVG in dp. Interested in your thoughts on this, maybe there is a better way by editing the source svg instead

**Comment by BigBadaboom** [comment]
Independent of the size it is actually rendered at on screen you mean?  So that if the ImageView was resized, the stroke width would remain the same?  If implemented, that would in, general, require the SVG to be re-rendered on resize.  I would need to modify SVGImageView.

If on the other hand, you just need to be able to specify dp units in an SVG. For example when you are displaying the SVG at 1:1. Then that is a simpler proposition.

**Comment by AlecStrong** [comment]
Correct, same strokewidth regardless of the rendered size. My use case is rendering to a canvas (via the renderToPicture api first), which does require re-rendering the SVG whenever the size changes.

That said, I might be able to get away with just rendering the SVG initially with a stroke width specified in dp. Especially when the cost of rendering is high

**Comment by BigBadaboom** [comment]
Fixed. (?)

This use case should be possible using the combination of two features implemented a while ago:
- `vector-effect="non-scaling-stroke"` (in version 1.2.0), and
- external CSS stylesheets (in version 1.3)

So I am going to close this issue on that assumption.  If I am wrong, feel free to follow up, and I will reopen.
