### ISSUE TITLE
SVG getting broken in Toolbar if using SDK 26

### ISSUE THREAD

**Issue by MinkiPan** [BigBadaboom/androidsvg#113]
Anyone facing the same issue? Is this a bug from support library?

left pic SDk26, right pic with SDK 25 
![screen shot 2017-07-31 at 12 35 35](https://user-images.githubusercontent.com/24230677/28774315-42a86e5a-75ed-11e7-9562-bdd51523948c.png)

**Comment by BigBadaboom** [comment]
You are using SVGs using AndroidSVG in your toolbar, rather than PNGs or VectorDrawables?

If so, I doubt that this will have anything to do with AndroidSVG.  You should report this to Google.  You may need to try it without the support library, so you can narrow down whether it is that - or 26/"O" itself.

But I'll leave this open for a day or two in case someone has useful info.  If you find mor information that suggests it is an AndroidSVG fault, please post more info (source etc).

**Comment by BigBadaboom** [comment]
No followup received. Marking closed.
