### ISSUE TITLE
The <clipPath> tag is invalid in some SDK

### ISSUE THREAD

**Issue by ckyA** [BigBadaboom/androidsvg#150]

**Comment by BigBadaboom** [comment]
Could you explain what you mean please?

Which SDK are you using?  And which version of AndroidSVG are you testing against?  If you are talking about Android P, then this issue will be fixed in the 1.3 release, which is due very soon.

Instructions for using the snapshot release can be found on the following page:
http://bigbadaboom.github.io/androidsvg/release-1.3.html

**Comment by ckyA** [comment]
I use the old version.... Thank you, I will close this issue soon
