### ISSUE TITLE
Font embedding broken in 1.3

### ISSUE THREAD

**Issue by latsson** [BigBadaboom/androidsvg#157]
I noticed when I updated to 1.3 from 1.2.1 that the embedded font did not work anymore.
See this example svg https://css-tricks.com/wp-content/uploads/2018/06/teams-nano.svg

In 1.3 it will be some serif default font.

If you need more info or a sample project with the issue just let me know.

Thanks

**Comment by BigBadaboom** [comment]
[teams-nano.zip](https://github.com/BigBadaboom/androidsvg/files/2419700/teams-nano.zip)

**Comment by BigBadaboom** [comment]
Hi. Thanks for your report.

AndroidSVG has never supported embedded fonts. It doesn't support `@font-face`.  What I think you are likely seeing is that in 1.3 the default font family was changed from "sans-serif" to "serif" to match the behaviour of browsers and other SVG renderers.

On Android the default sans-serif font is Roboto, so the correct font was being displayed in 1.2 - by accident really.

There are a few things you can do:

1. Change your SVGs to use `font-family: sans-serif`
2. Pass an implementation of `SVGExternalFileResolver` to the renderer (using `SVG.registerExternalFileResolver(myResolver);`). Make it return `Typeface.SANS_SERIF` from its `resolveFont()` method
3. Put a copy of the Roboto font in your assets folder, and pass an instance of `SimpleAssetResolver` to the renderer.  It will load the Roboto font from your assets folder and use it 

The first two options will result in similar behaviour as 1.2, but if the default Android font ever changes, then it will display that font instead of Roboto.
