### ISSUE TITLE
Problem with drawing SVG on view canvas

### ISSUE THREAD

**Issue by mindvv0rk** [BigBadaboom/androidsvg#165]
I try to render [this svg](https://drive.google.com/file/d/1WoBKWDRVLT7UBkLYWd3lfULmuLlqkAnJ/view?usp=sharing) on canvas view.

How i prepare svg:
```
val svg: SVG = SVG.getFromAsset(context.assets, "bg_2.svg")
    if (svg.documentWidth != -1f)
    {

        val density = resources.displayMetrics.density
        svg.documentHeight *= density
        svg.documentWidth *= density
    }
```

How i draw svg:
```
override fun onDraw(canvas: Canvas) {
        super.onDraw(canvas)

        canvas.drawRGB(255, 255, 255)

        svg.renderToCanvas(canvas)
    }
```

But [result image looks not good](https://drive.google.com/file/d/12357UHgjRUOl35OzLsJKeYs6TwmNDUiB/view?usp=sharing) , on edges i can see pixels. 

If create separate canvas with bitmap and than draw bitmap on view canvas [image looks good](https://drive.google.com/file/d/1nopshE1txxkZAxAnshtzXdWQDJEddj48/view?usp=sharing): 
```
val bitmap = Bitmap.createBitmap(
  Math.ceil(svg.documentWidth.toDouble()).toInt(),
  Math.ceil(svg.documentHeight.toDouble()).toInt(),
  Bitmap.Config.ARGB_8888
  )
val bmCanvas = Canvas(bitmap)

...

override fun onDraw(canvas: Canvas) {
        super.onDraw(canvas)

        canvas.drawRGB(255, 255, 255)

        svg.renderToCanvas(bmCanvas)
        canvas.drawBitmap(bitmap, 0f, 0f, null)
}
```

Is this a bug or i do something wrong?

**Comment by BigBadaboom** [comment]
Hi

Have you tried just doing this?

val svg: SVG = SVG.getFromAsset(context.assets, "bg_2.svg")
svg.documentHeight = "100%"
svg.documentWidth = "100%"

**Comment by mindvv0rk** [comment]
Hi!


Try this, however result is the same.
> ```
> val svg: SVG = SVG.getFromAsset(context.assets, "bg_2.svg")
> svg.documentHeight = "100%"
> svg.documentWidth = "100%"
> ```



This all [view code](https://gist.github.com/mindvv0rk/53f4e792b17e6c0327210d2bf14efce7), if it help.

**Comment by BigBadaboom** [comment]
Hmm.. Any chance that you can put together a little test app with your view and the SVG?  So I can try it locally?

**Comment by mindvv0rk** [comment]
Yes, i create repo with simple sample project https://github.com/mindvv0rk/SvgExampleApp.

Thank you!

**Comment by BigBadaboom** [comment]
Hi. Sorry it took so long to get to this.  I finally had the time to investigate this weekend.

Turns out this is a "bug" with the Android's hardware 2D renderer.  Romain Guy of Google explains the problem in his answer to this Stack Overflow question: https://stackoverflow.com/questions/16090607/blurry-offset-paths-when-canvas-is-scaled-under-hardware-acceleration

To summarise: when you have an SVG like the following:

    <g transform="translate(8 7)">
      <path d="..."/>
    </g>

What AndroidSVG converts this to is the following (slightly simplified)

    canvas.scale(8, 7);
    canvas.drawPath(path);

Unfortunately, how the hardware 2D render handles these calls is to render the path at `scale(1,1)` into a buffer, then draw that buffer onto the screen at `scale(8,7)`. The scaled up bitmap buffer will be getting bilinearly interpolated. Thus causing the extra blurriness that you are seeing.

Unfortunately due to the way transforms are defined to work in SVG, there isn't anything I can do about this.  We just have to wait and hope that Google fix the hardware renderer (Skia).  But considering that it has likely been like that since it was created, that's probably not likely to change any time soon.

The only work-arounds are:

1. Remove all `transform` attributes from your SVG and only ever render the SVG at 1:1 scale (ie no `viewBox`), or
2. Render into a bitmap yourself first.  This will use the software renderer, which does not have this fault.

Sorry I don't have better news for you.

**Comment by BigBadaboom** [comment]
I created an Android bug report to see if we can get any action on this fault.

https://issuetracker.google.com/issues/130081361

**Comment by kpeeters** [comment]
Sorry to re-open this thread. I am trying to use method 2 to be compatible with older devices, but I can't seem to find the right combination of calls. I tried

    bitmap = Bitmap.createBitmap(128, 128, Bitmap.Config.ARGB_8888)
    canvas = Canvas(bitmap)
    svgImage.renderToCanvas(canvas, renderOpts)
    image.setImageBitmap(bitmap)

to force it to render to a 128x128 bitmap, but that does not scale the view to maximal size: an SVG
with 

    <svg height="24" viewBox="0 0 24 24" width="24">

appears as a small blob in the top-left corner of the bitmap. I tried adding

    renderOpts.viewPort(0.0f, 0.0f, 128.0f, 128.0f)

to my render options (which in addition to this only has some css recolouring), but that makes no difference.

The ImageView has an explicit width/height set in dp, and scaleType="fitCenter".

Any help is much appreciated!

**Comment by BigBadaboom** [comment]
Hi @kpeeters

Unless you override the SVG's `width` and `height` attributes, it will always be drawn at 24x24 px.  Please see this FAQ question tfor how to fix that:

[My document has a viewBox, but it is still not scaling](http://bigbadaboom.github.io/androidsvg/faq.html#My_document_has_a_viewBox,_but_it_is_still_not_scaling)

**Comment by kpeeters** [comment]
I tried doing

    svg.setDocumentWidth("100%");
    svg.setDocumentHeight("100%");

but that did not solve the problem; the images are still blurry. In addition, I don't seem to need this on VERSION_CODE.P or higher, where everything was already rendering sharp. So maybe it's not quite the same issue as in the FAQ (which seems to discuss a problem which appears on every android version).

However, I meanwhile figured out that

    if (android.os.Build.VERSION.SDK_INT < android.os.Build.VERSION_CODES.P) {
	    image.setLayerType(View.LAYER_TYPE_SOFTWARE, null)
    }

*does* fix it.

Thanks for making this wonderful library available!

**Comment by BigBadaboom** [comment]
Okay.  Great.  I'm glad that worked for you.
