### ISSUE TITLE
Question: Would on-device SVG conversion to AVD be feasible?

### ISSUE THREAD

**Issue by stefanhaustein** [BigBadaboom/androidsvg#188]
This would presumably allow to re-use existing rendering infrastructure?

**Comment by BigBadaboom** [comment]
Hi Stefan

By "AVD" do you mean AnimatedVectorDrawable?  You are suggesting implementing animation by convert an animated SVG to an AnimatedVectorDrawable.  Is that what you mean?

In theory you could do the conversion.  But I think you are then stuck because AFAIK there is no way to get Android to load a resource from app memory.  They have to be resources in the apps `res` folder.

Paul

**Comment by stefanhaustein** [comment]
I was referring to regular AndroidVectorDrawables. But I think the problem is the same... Thanks for the clarification!
