### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=0; index=-2 in SVGAndroidRenderer.arcTo(SourceFile:2572)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BigBadaboom/androidsvg#62]
```
What steps will reproduce the problem?
No specific steps to reproduce.

java.lang.ArrayIndexOutOfBoundsException: length=0; index=-2
at com.caverock.androidsvg.SVGAndroidRenderer.arcTo(SourceFile:2572)
at com.caverock.androidsvg.SVGAndroidRenderer.access$5(SourceFile:2463)
at 
com.caverock.androidsvg.SVGAndroidRenderer$PathConverter.arcTo(SourceFile:2437)
at com.caverock.androidsvg.SVG$PathDefinition.enumeratePath(SourceFile:2024)
at 
com.caverock.androidsvg.SVGAndroidRenderer$PathConverter.<init>(SourceFile:2394)
at com.caverock.androidsvg.SVGAndroidRenderer.render(SourceFile:972)
at com.caverock.androidsvg.SVGAndroidRenderer.render(SourceFile:298)
at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SourceFile:330)
at com.caverock.androidsvg.SVGAndroidRenderer.render(SourceFile:584)
at com.caverock.androidsvg.SVGAndroidRenderer.renderDocument(SourceFile:267)
at com.caverock.androidsvg.SVG.renderToPicture(SourceFile:306)
at com.caverock.androidsvg.SVG.renderToPicture(SourceFile:282)
at com.caverock.androidsvg.SVGImageView.setSVG(SourceFile:116)

What is the expected output? What do you see instead?
No crashes

What version of the product are you using? On what operating system?
- com.caverock:androidsvg:1.2.1
- Android 4.4.2 & 4.4.4

Please provide any additional information below.
Probably, in the latest code base, java.lang.ArrayIndexOutOfBoundsException is 
thrown from the following line:
https://code.google.com/p/androidsvg/source/browse/src/com/caverock/androidsvg/S
VGAndroidRenderer.java#2658
```

Original issue reported on code.google.com by `yonghoo...@gmail.com` on 8 May 2015 at 12:10

**Comment by ndahlquist** [comment]
Okay, finally got a STR. It's a little involved.
  1. Here is an SVG that repros the issue: https://github.com/Snapchat/androidsvg/blob/e658fb4112108d05ebc7d02a53de53f218b8841e/testapp/src/main/res/drawable/snapcode.svg.
 2. Proguard has to be enabled.
 3. It does not crash on the first call to render, but happens on the second call.

Here is a standalone test app that repros the issue: https://github.com/Snapchat/androidsvg/commit/e658fb4112108d05ebc7d02a53de53f218b8841e. It will crash if you switch to landscape / portrait to force a re-render.

**Comment by ndahlquist** [comment]
This is quite the fascinating bug. I have determined that `angleExtent` in `com.caverock.androidsvg.SVGAndroidRenderer#arcTo` is `NaN`. The bug does not appear to maniphest itself on specific input values; what appear to be the same arguments to `arcTo()` sometimes crash and sometimes do not. However, it is difficult to debug, because inserting log statements to get the values of intermediate variables causes the bug to disappear. This suggests to me that the issue is probably a bug in the Android 4.4.2 and 4.4.4 JVMs handling of doubles.

I was not able to prevent the issue with a proguard switch (the '-dontoptimize' flag does not seem to help...?), but a workaround is to just swap out the doubles in this function with floats. @BigBadaboom Are you particularly invested in double-precision within this function, or would you accept a PR to use floats instead?

**Comment by BigBadaboom** [comment]
Fixed.  Thanks Nic!
