### ISSUE TITLE
XML parser insecure - XXE

### ISSUE THREAD

**Issue by martinvigo** [BigBadaboom/androidsvg#69]
Looking at how the XML parser is declared, it looks like it is vulnerable to XXE. You can read on it here: https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Processing 

To prevent Billion laughs attacks, etc I suggest adding:
```
// Using the SAXParserFactory's setFeature
spf.setFeature("http://xml.org/sax/features/external-general-entities", false);

// Using the XMLReader's setFeature
xr.setFeature("http://xml.org/sax/features/external-general-entities", false);
```

**Comment by mstevens83** [comment]
I'll have a go at this and will submit a PR.

**Comment by BigBadaboom** [comment]
Just looking at this now.  I don't believe AndroidSVG is vulnerable to these attacks because we aren't providing a URL resolver (for external references) when we parse.

Technically we are vulnerable to the Billion Laughs attach, but I think it's safe to assume that app developers won't normally try to crash users' phones.

I don't really want to disable all entity expansion, because there are some SVG generators that produce files with entities.  I would enable FEATURE_SECURE_PROCESSING, but the Harmony/Expat SAXParser, that Android currently uses, doesn't support that.

So I am going to mark this as a Won't Fix for now.  Maybe when Android switch to the JDK, we may be able to enable it then.

**Comment by mstevens83** [comment]
I agree it makes sense to have a look at this again when/if Android goes JDK. I'll try to remind you ;-).
