### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by vinhtq** [BigBadaboom/androidsvg#77]
I found this project but lastest update was 2 years ago. I wonder does the author keep developing this project?

**Comment by BigBadaboom** [comment]
It's not abandoned.  I have just been very busy.

It hasn't been two years.  The last update to 1.2 was just over a year ago. But there has been work in another local clone that I have.

If you have a question about the status of the project. Please email me at androidsvgfeedback@gmail.com, rather than opening an issue.

Thanks.
