### ISSUE TITLE
Emoji rendering issue on Android M

### ISSUE THREAD

**Issue by siwusc** [BigBadaboom/androidsvg#82]
the decorations will go out of border or have wrong shapes, some examples below

![device-2016-01-10-145005](https://cloud.githubusercontent.com/assets/11927520/12303669/767a5312-b9e0-11e5-82d3-142d129c97bf.png)

**Comment by BigBadaboom** [comment]
Hi Alycia

Can you attach a sample SVG that doesn't render correctly?  Are you using the SVGImageView widget, or rendering it yourself?

**Comment by siwusc** [comment]
Sorry for the delay, we are using svg.renderToCanvas(canvas) in some places and SVGImageView in other places, it seems both rendering methods are having the same problem.

https://github.com/twitter/twemoji/blob/gh-pages/svg/1f3c0.svg
https://github.com/twitter/twemoji/blob/gh-pages/svg/1f3c9.svg

**Comment by BigBadaboom** [comment]
Hi Alyicia.  What version of Android are you getting this fault on?

I have been able to reproduce this bug in Android 6.0.1.  After some investigation, it appears these rendering issues are because there is bug - actually two of them - in Canvas and Picture classes.  It is very similar to the Android bug that was affecting clip paths in Android 4.3.

Unfortunately, the only workaround is to stick to using SVGs that don't use the <clipPath> element.

**Comment by BigBadaboom** [comment]
For reference, the Android bug is at: https://code.google.com/p/android/issues/detail?id=200128

**Comment by siwusc** [comment]
I see, thank you so much for the help!
