### ISSUE TITLE
Any workaround for clippath?

### ISSUE THREAD

**Issue by alexandre-g** [BigBadaboom/androidsvg#94]
Does anyone know of a workaround for the Android 6.0 clip path issue?
Haven't experimented much, but does not render with `renderToCanvas()` on Android 5 correctly either..

**Comment by BigBadaboom** [comment]
Not currently.  The Skia people have suggested an approach that may work around the problem, but I haven't had the time to investigate it yet.

In the meantime, the only workaround, really, is to apply the clip path to your objects so their shapes are physically clipped (ie modified geometry) rather than relying on <clipPath> elements.

**Comment by BigBadaboom** [comment]
Fixed in current tree. Will be in the next release.  To use right now, build the library from source.

- Implemented a new way to do clipPaths.
- The new method works on all 4.4 (K) and later devices.
- Clip paths are more accurate, handle clip-rule properly, and work for renderToPicture().
- Works around the bug in Android 6.0 that mangles clip paths on canvas.restore().
